### ISSUE TITLE
Problems running iLiSA on LOFAR station in Latvia

### ISSUE THREAD

**Issue by sklandrausis** [2baOrNot2ba/iLiSA#2]
Hi!

I have recently installed iLiSA on the LOFAR station in Latvia.

executing command ilisa_obs  ilsa_test_bst.yml I got this error

2022-09-09T10:39:05.505 | INFO | On LCU> swlevel -V
2022-09-09T10:39:29.600 | INFO | Established access to LCU on LV614.
2022-09-09T10:39:29.601 | INFO | On LCU> env | grep '^PATH'
2022-09-09T10:39:54.411 | INFO | On LCU> ls /data/home/user1/.cache/ilisa/BSX_data/
2022-09-09T10:40:19.147 | INFO | On LCU> ls /data/home/user1/.cache/ilisa/ACC_data/
2022-09-09T10:40:43.831 | INFO | On LCU> cat /opt/lofar_local/etc/RSPDriver.conf
Traceback (most recent call last):
  File "/usr/local/bin/ilisa_obs", line 11, in <module>
    load_entry_point('iLiSA==6.3', 'console_scripts', 'ilisa_obs')()
  File "/usr/local/lib/python3.8/dist-packages/iLiSA-6.3-py3.8.egg/ilisa/operations/scansession.py", line 589, in main_cli
    obs(scansess_in, sac)
  File "/usr/local/lib/python3.8/dist-packages/iLiSA-6.3-py3.8.egg/ilisa/operations/scansession.py", line 532, in obs
    stndrv = StationDriver(sac['LCU'], sac['DRU'], mockrun=mockrun)
  File "/usr/local/lib/python3.8/dist-packages/iLiSA-6.3-py3.8.egg/ilisa/operations/stationdriver.py", line 103, in __init__
    self.tbbraw2h5cmd = accessconf_dru['TBBraw2h5Cmd']
KeyError: 'TBBraw2h5Cmd'
2022-09-09T10:41:08.834 | INFO | On LCU> killall beamctl
Exception ignored in: <function StationDriver.__del__ at 0x7ff09d199790>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/iLiSA-6.3-py3.8.egg/ilisa/operations/stationdriver.py", line 202, in __del__
    if self.halt_observingstate_when_finished:
AttributeError: 'StationDriver' object has no attribute 'halt_observingstate_when_finished'

file   ilsa_test_bst.yml content
scans:
  - beam:
      freqspec: '10e6:90e6'
      pointing: Cas-A
    rec: [bst]
    integration:  0.5
    duration: 60

What can be a potential fix for this error?

Best regards,
Jānis Šteinbergs.

**Comment by 2baOrNot2ba** [comment]
Dear Jānis,
it is not possible with the `bst` recording mode to integrate below 1.0 second. In fact, bst integration can only be whole seconds. So requesting 0.5 seconds is *not* possible. This has to do with the design of LOFAR rather the iLiSA package (it should probably do a better job of informing the user though, I will admit). If you want to go below 1.0 second you need to record `bfs` mode and then have a streaming or post-processing with pipeline S/W.

**Comment by 2baOrNot2ba** [comment]
I realize belatedly, that another issue is behind this. It is not really the sub-second integration - although that is still true, lofar stats data can only be integrated at integer second steps - it is that the `TBBraw2h5Cmd` was not set in the `access_lclstn.conf` file.

**Comment by 2baOrNot2ba** [comment]
So I fixed the issue of the missing `TBB` access conf parameters in commit 603c081c98c73e4e5aad369a67914ccc1c0d5301 by just setting them to `None` by default.
